[versions]
agp = "8.2.2"
coroutines = "1.8.0"
kotlin = "1.9.24"
kotest = "5.9.0"
ktor = "3.0.0-eap-852"
kx-io = "0.3.4"

[libraries]
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }
kotest-framework-datatest = { group = "io.kotest", name = "kotest-framework-datatest", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
ktor-network = { group = "io.ktor", name = "ktor-network", version.ref = "ktor" }
kx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kx-io" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
