name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  linux-build:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install chromium-browser epiphany-browser firefox
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        env:
          SAFARI_BIN: epiphany-browser
        run: ./gradlew build
  macos-build:
    name: Build on macOS
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew build
